sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx-2
notifications:
  flowdock:
    secure: fSZxX5z3bHWT8aCFKBFrDDt5o3Jb6EFWcm+pAcMabpfDHc4iktWuCUlSM405798TRdKdws1A2RncQGYiQyLbqNvtLz48dvj4BxgYW7P/vg0koN+I/H2MjpZeuIQ7BRSEJIq2sAYNVya+hSil+SPEBMTngJiP6VYG0dm6fFnRkyk=
